// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleSecureCoding.Data;

#nullable disable

namespace SampleSecureCoding.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241009054318_Tambah_Table_User")]
    partial class Tambah_Table_User
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SampleSecureCoding.Models.Student", b =>
                {
                    b.Property<string>("NIM")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NIM");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
